resources:
  - url: http://127.0.0.1:5000/podcast-card.js
    type: module
views:
  - cards:
      - type: "custom:podcast-card"
        entity: sensor.gpodder
        name: Ian's Podcasts
        show_player: true
        custom_player: false
